### ISSUE TITLE
autocompler is error : No such file or directory

### ISSUE THREAD

**Issue by czfshine** [kleientertainment/ds_mod_tools#5]
Hi~~ I want to improve my english.
Today I clone the ds_mod_tools into my PC,make is succeed .
But I cd to ./build/linux/mod_tools  ,Run ./autocompler ,it say No such file or directory.
My computer system is ubuntu 14.04.

Like this:

czfshine@czfshine:/mnt/d/mods/ds_mod_tools-master/build/linux/mod_tools$ ./autocompiler 
/usr/bin/python2.7

Atlasing ./../../dont_starve/mods/wand/images/inventoryimages/wand.png npot: False
Atlasing
Traceback (most recent call last):
  File "./compiler_scripts/image_build.py", line 110, in <module>
    process_file_to_atlas()
  File "./compiler_scripts/image_build.py", line 100, in process_file_to_atlas
    ignore_exceptions=args.ignoreexceptions, generate_mips=True) #, no_premultiply=im.mode=='RGB' )
  File "/mnt/d/mods/ds_mod_tools-master/build/linux/mod_tools/buildtools/linux/Python27/Lib/site-packages/klei/textureconverter.py", line 113, in Convert
    if subprocess.call( cmd_list ) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR: Command failed!

Log:
compiler registered: ./png
compiler registered: ./scml

> > Compiling ./../../dont_starve/mods/wand/images/inventoryimages/wand.png.
# 

"./png" "./../../dont_starve/mods/wand/images/inventoryimages/wand.png" "./../../dont_starve/mods/wand"

> > Compiling './../../dont_starve/mods/wand/images/inventoryimages/wand.png'
# 

"python2.7" "./compiler_scripts/image_build.py" "./../../dont_starve/mods/wand/images/inventoryimages/wand.png"

ERROR: Command failed!

**Comment by a8568730** [comment]
The error occurs when the [ktools](https://github.com/nsimplex/ktools#installation-from-source) is not installed.
We found the complete build autocompiler process as below:
```bash
# NOTE:
# {DST_ROOT} means the DST root directory: 
# ~/.local/share/Steam/steamapps/common/Don\'t\ Starve\ Together/
```
Step. Install and clone tools
```bash
$ cd {DST_ROOT}
$ sudo apt-get install cmake libmagick++-dev 
$ sudo apt-get install premake4 
$ git clone git@github.com:nsimplex/ktools.git
$ git clone git@github.com:kleientertainment/ds_mod_tools.git
```
Step. Build and install ktools
```bash
$ cd ./ktools/
$ ./configure && make
$ sudo make install
```
Step. Build ds_mod_tools autocompiler
```bash
$ cd ../ds_mod_tools/src/
$ bash premake.sh
$ cd ../build/proj/
$ make
```
Step. Copy autocompiler to DST_ROOT
```bash
$ cp ../
$ cp  -r ./linux {DST_ROOT}
```
Step. Copy your mod directory to DST_ROOT
```bash
$ cp  -r ~/home/MyCharacter/ {DST_ROOT}
```
Step. Rock!
```bash

$ cd {DST_ROOT}/linux/mod_tools/
$ ./autocompiler
```
